CREATE DATABASE [IdentityDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IdentityDB', FILENAME = N'D:\rdsdbdata\DATA\IdentityDB.mdf' , SIZE = 5120KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'IdentityDB_log', FILENAME = N'D:\rdsdbdata\DATA\IdentityDB_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [IdentityDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IdentityDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IdentityDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IdentityDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IdentityDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [IdentityDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [IdentityDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IdentityDB] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [IdentityDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IdentityDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IdentityDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IdentityDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IdentityDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IdentityDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IdentityDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IdentityDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [IdentityDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IdentityDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IdentityDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IdentityDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [IdentityDB] SET  READ_WRITE 
GO
ALTER DATABASE [IdentityDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [IdentityDB] SET  MULTI_USER 
GO
ALTER DATABASE [IdentityDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IdentityDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [IdentityDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [IdentityDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [IdentityDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [IdentityDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

CREATE DATABASE [CatalogDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CatalogDB', FILENAME = N'D:\rdsdbdata\DATA\CatalogDB.mdf' , SIZE = 5120KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'CatalogDB_log', FILENAME = N'D:\rdsdbdata\DATA\CatalogDB_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CatalogDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CatalogDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CatalogDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CatalogDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CatalogDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CatalogDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CatalogDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CatalogDB] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [CatalogDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CatalogDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CatalogDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CatalogDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CatalogDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CatalogDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CatalogDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CatalogDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CatalogDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CatalogDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CatalogDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CatalogDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CatalogDB] SET  READ_WRITE 
GO
ALTER DATABASE [CatalogDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CatalogDB] SET  MULTI_USER 
GO
ALTER DATABASE [CatalogDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CatalogDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CatalogDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CatalogDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [CatalogDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [CatalogDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
