CREATE DATABASE [eShopOnWeb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eShopOnWeb', FILENAME = N'/var/opt/mssql/data/eShopOnWeb.mdf' , SIZE = 5120KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'eShopOnWeb_log', FILENAME = N'/var/opt/mssql/data/eShopOnWeb_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [eShopOnWeb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [eShopOnWeb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [eShopOnWeb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [eShopOnWeb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [eShopOnWeb] SET ARITHABORT OFF 
GO
ALTER DATABASE [eShopOnWeb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [eShopOnWeb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [eShopOnWeb] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [eShopOnWeb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [eShopOnWeb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [eShopOnWeb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [eShopOnWeb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [eShopOnWeb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [eShopOnWeb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [eShopOnWeb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [eShopOnWeb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [eShopOnWeb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [eShopOnWeb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [eShopOnWeb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [eShopOnWeb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [eShopOnWeb] SET  READ_WRITE 
GO
ALTER DATABASE [eShopOnWeb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [eShopOnWeb] SET  MULTI_USER 
GO
ALTER DATABASE [eShopOnWeb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [eShopOnWeb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [eShopOnWeb] SET DELAYED_DURABILITY = DISABLED 
GO
USE [eShopOnWeb]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [eShopOnWeb]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [eShopOnWeb] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
